services:
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: menufinder
      POSTGRES_PASSWORD: menufinder
      POSTGRES_DB: menufinder
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
